import "../style/globals.css";
import type { Metadata } from "next";
import Theme from "../Theme/themeRegistry";
import { CssBaseline } from "@mui/material";
import StyledComponentsRegistry from "./registry";
export const metadata: Metadata = {
  title: "hivad Parvaz kish",
  description: "Generated by pouyagaran saze aryan",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" dir="rtl">
      <Theme>
        <CssBaseline />
        <body>
          <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
        </body>
      </Theme>
    </html>
  );
}
