import "./globals.css";
import type { Metadata } from "next";
import Theme from "./Theme/themeRegistry";

export const metadata: Metadata = {
  title: "hivad Parvaz kish",
  description: "Generated by pouyagaran saze aryan",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <Theme>
        <body>{children}</body>
      </Theme>
    </html>
  );
}
