import "./globals.css";
import type { Metadata } from "next";
import Theme from "./Theme/themeRegistry";
import { CssBaseline } from "@mui/material";
export const metadata: Metadata = {
  title: "hivad Parvaz kish",
  description: "Generated by pouyagaran saze aryan",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" dir="rtl">
      <Theme>
        <CssBaseline />

        <body>{children}</body>
      </Theme>
    </html>
  );
}
